- hosts: controls
  become: yes
  tasks:
    - name: initialize the cluster
      shell: kubeadm init --pod-network-cidr=10.244.0.0/16
      args:
        chdir: $HOME
        creates: cluster_initialized.txt

    - name: create .kube directory
      become: yes
      become_user: fullaware
      file:
        path: $HOME/.kube
        state: directory
        mode: 0755

    - name: copies admin.conf to user's kube config
      copy:
        src: /etc/kubernetes/admin.conf
        dest: /home/fullaware/.kube/config
        remote_src: yes
        owner: fullaware

    - name: install Pod network
      become: yes
      become_user: fullaware
      shell: kubectl apply -f https://projectcontour.io/quickstart/contour.yaml
      args:
        chdir: $HOME