---
- hosts: controls
  become: yes
  gather_facts: false
  tasks:
    - name: Get the token for joining the worker nodes
      become: yes
      become_user: ubuntu
      shell: kubeadm token create  --print-join-command
      register: kubernetes_join_command

    - debug:
        msg: "{{ kubernetes_join_command.stdout }}"

- hosts: workers
  become: yes
  tasks:

    - name: Join the Worker nodes to the cluster.
      become: yes
      command: kubeadm join 10.28.28.60:6443 --token qcbvgv.3xqrwpoats5kh0pa --discovery-token-ca-cert-hash sha256:f7c26528a59288ba80bbf3c9f26626895a54879f50e4d5febd1597196ae3727a
      register: joined_or_not