- hosts: controls
  become: yes
  tasks:
    - name: initialize the cluster
      shell: kubeadm init --pod-network-cidr=10.244.0.0/16
      args:
        chdir: $HOME
        creates: cluster_initialized.txt

    - name: create .kube directory
      become: yes
      become_user: ubuntu
      file:
        path: $HOME/.kube
        state: directory
        mode: 0755

    - name: copies admin.conf to user's kube config
      copy:
        src: /etc/kubernetes/admin.conf
        dest: /home/ubuntu/.kube/config
        remote_src: yes
        owner: ubuntu

    - name: copies kubeconfig locally as kubeconfig.yaml
      fetch:
        src: /home/ubuntu/.kube/config
        dest: ./kubeconfig.yaml
        flat: yes

    - name: install Pod network Antrea
      become: yes
      become_user: ubuntu
      shell: kubectl apply -f https://raw.githubusercontent.com/antrea-io/antrea/main/build/yamls/antrea.yml
      args:
        chdir: $HOME
