---
- hosts: controls
  become: yes
  become_method: sudo
  gather_facts: true
  tasks:
    - name: Get the token for joining the nodes with Kuberentes master.
      shell: kubeadm token create  --print-join-command
      register: kubernetes_join_command
    - debug:
        msg: "{{ kubernetes_join_command.stdout }}"
    - name: Copy join command to local file.
      become: yes
      become_method: sudo
      local_action: copy content="{{ kubernetes_join_command.stdout_lines[0] }}" dest="/tmp/kubernetes_join_command" mode=0755

- hosts: workers
  become: yes
  tasks:
    - name: Copy join command to worker nodes.
      become: yes
      become_method: sudo
      copy:
        src: /tmp/kubernetes_join_command
        dest: /tmp/kubernetes_join_command
        mode: 0777   
    - name: Join the Worker nodes with the master.
      become: yes
      become_method: sudo
      command: sh /tmp/kubernetes_join_command
      register: joined_or_not
    - debug:
        msg: "{{ joined_or_not.stdout }}"