- hosts: controls
  become: yes
  tasks:
    - name: install metrics-server
      become: yes
      become_user: ubuntu
      shell: kubectl apply -f https://github.com/kubernetes-sigs/metrics-server/releases/latest/download/components.yaml
      args:
        chdir: $HOME

    - name: copying patch to server to allow insecure TLS
      become: true 
      copy:
        src: ./patch-metrics-server.yaml
        dest: /home/ubuntu/patch-metrics-server.yaml
        mode: 0777

    - name: patch metrics-server
      become: yes
      become_user: ubuntu
      shell: kubectl -n kube-system patch deploy metrics-server --patch-file patch-metrics-server.yaml
      args:
        chdir: $HOME

    - name: Install OpenEBS operator for storage
      become: yes
      become_user: ubuntu
      shell: kubectl apply -f https://openebs.github.io/charts/openebs-operator-lite.yaml 
      args:
        chdir: $HOME

    - name: Install OpenEBS for HostPath PV storageclass
      become: yes
      become_user: ubuntu
      shell: kubectl apply -f https://openebs.github.io/charts/openebs-lite-sc.yaml
      args:
        chdir: $HOME

    - name: copying patch storageclass openebs-hostpath to be default
      become: true 
      copy:
        src: ./patch-storageclass.yaml
        dest: /home/ubuntu/patch-storageclass.yaml
        mode: 0777

    - name: patch storageclass openebs-hostpath to be default
      become: yes
      become_user: ubuntu
      shell: kubectl patch storageclass openebs-hostpath --patch-file patch-storageclass.yaml
      args:
        chdir: $HOME

    - name: Install Metatllb Load Balancer
      become: yes
      become_user: ubuntu
      shell: kubectl apply -f https://raw.githubusercontent.com/metallb/metallb/v0.13.7/config/manifests/metallb-native.yaml
      args:
        chdir: $HOME

    - name: copying apply-metallb-config.yaml
      become: true 
      copy:
        src: ./apply-metallb-config.yaml
        dest: /home/ubuntu/apply-metallb-config.yaml
        mode: 0777

    - name: apply metallb-config IPAddressPool and L2Advertisement
      become: yes
      become_user: ubuntu
      shell: kubectl apply -f apply-metallb-config.yaml
      args:
        chdir: $HOME

    - name: Install Contour for L7 Ingress
      become: yes
      become_user: ubuntu
      shell: kubectl apply -f https://projectcontour.io/quickstart/contour.yaml
      args:
        chdir: $HOME

    - name: Install Portainer Business Edition (Free for 5 nodes) using LoadBalancer
      become: yes
      become_user: ubuntu
      shell: kubectl apply -n portainer -f https://downloads.portainer.io/ee2-16/portainer-lb.yaml
      args:
        chdir: $HOME


