- hosts: controls
  become: yes
  tasks:
    - name: copies kubeconfig locally as kubeconfig.yaml
      fetch:
        src: /home/ubuntu/.kube/config
        dest: ./kubeconfig.yaml
        flat: yes
